### PR TITLE
feat(release-please): add release-please to default module configuration

### PR DESCRIPTION
**Pull request by gberenice**
## Info
Adds release-please work introduced by @Gowiem in https://github.com/masterpointio/terraform-aws-tailscale/pull/25. We need this for each module in the Org.

### CODE REVIEW

**Review by Gowiem — APPROVED** [review]
Did our first release for the tailscale module here: https://github.com/masterpointio/terraform-aws-tailscale/releases/tag/v1.3.0

I think I like it? It requires that we merge an extra PR, which is a bit overkill for single change releases... but it automates away some of the tedium and gives us a consistent system to utilize. 

Any thoughts before we adopt this fully @gberenice @oycyc?

**Comment by oycyc** [comment]
> Did our first release for the tailscale module here: https://github.com/masterpointio/terraform-aws-tailscale/releases/tag/v1.3.0
> 
> I think I like it? It requires that we merge an extra PR, which is a bit overkill for single change releases... but it automates away some of the tedium and gives us a consistent system to utilize.
> 
> Any thoughts before we adopt this fully @gberenice @oycyc?

I like it too, it's cleaner output and also even though we merge an extra PR, that step is substitutes us manually creating the release. `single change releases` if we don't want to create a release for something minor, I guess we can leave the PR open.

We can also use this flag to just create a release every time merge to the default branch, kind of like CloudPosse module does with their custom script.
image

**Comment by gberenice** [comment]
> We can also use this flag to just create a release every time merge to the default branch, kind of like CloudPosse module does with their custom script. But I don't think it's too much extra work to merge that extra PR as an additional confirmation input from us. image

@oycyc hm, I wish it was that simple, but it doesn't seem to work:(
`release-please` is designed around the PR-based workflow, and this parameter allows to handle some cases when a user needs to split PR creation from release tagging.

Look how they do a release without PR: https://github.com/googleapis/release-please-action/blob/7987652d64b4581673a76e33ad5e98e3dd56832f/.github/workflows/release-please.yaml#L37-L61

>I think I like it? It requires that we merge an extra PR, which is a bit overkill for single change releases... but it automates away some of the tedium and gives us a consistent system to utilize.

@Gowiem I like the Cloudposse workflow more, but I'm fine with trying out the PR-based flow. If we find this approach tedious, we can add an auto-merge step (e.g. [enable-pull-request-automerge](https://github.com/peter-evans/enable-pull-request-automerge)) or tag creation without PR (as in the example above).

**Comment by Gowiem** [comment]
@gberenice yeah, I hear you on liking the CP way better. It may be that we build that out... for now since this is so simple + easy... let's go with this and see how we like it for a bit.

**Pull request merged**
